<RootLayout>:

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'top'

        CharacterDisplay:
            id: _character_display
            size_hint_y: None
            height: root.height - _option_bar.height

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'

        OptionBar:
            character_display: _character_display
            id: _option_bar
